on:
  push:
    branches: [main]
  schedule:
    - cron: '45 8 * * *'
  workflow_dispatch:

jobs:
  main:
    uses: deadsnakes/runbooks/.github/workflows/update-nightly.yml@main
    with:
      dists-json: '["focal", "jammy", "noble"]'
      version: 3.14
    secrets: inherit
